services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME:-mydatabase}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_USER: ${DB_USER:-myuser}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
