spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  liquibase:
    contexts: test
  mail:
    host: localhost
    port: 3025
    username: ""
    password: ""
    properties:
      "[mail.smtp.auth]": false
      "[mail.smtp.starttls.enable]": false
      "[mail.smtp.starttls.required]": false
debug: true
logging:
  level:
    '[org.springframework.security]': DEBUG
