spring:
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ${SPRING_APPLICATION_NAME:myapp}
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public-key.pem
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:smtp-user}
    password: ${MAIL_PASSWORD:smtp-password}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
    default-encoding: UTF-8
  data:
    web:
      pageable:
        page-parameter: p
        size-parameter: s
  cache:
    type: caffeine
    caffeine: 
      spec: maximumSize=1000,expireAfterWrite=10m
    cache-names:
      - project-permissions

info:
  app:
    name: ${APP_NAME:myapp}
    description: ${APP_DESCRIPTION:My Application}
    version: ${APP_VERSION:1.0.0}
    author: ${APP_AUTHOR:tianqueal}
    contactEmail: ${APP_CONTACT_EMAIL:user@example.com}
    contactUrl: ${APP_CONTACT_URL:https://example.com}
    license: ${APP_LICENSE_NAME:MIT}
    licenseUrl: ${APP_LICENSE_URL:https://opensource.org/license/mit}
    docsUrl: ${APP_DOCS_URL:http://localhost:8080/swagger-ui/index.html}
    server:
      dev:
        url: ${API_SERVER_DEV_URL:http://localhost:8080}
        description: ${API_SERVER_DEV_DESCRIPTION:Local Development Server}
      prod:
        url: ${API_SERVER_PROD_URL:http://localhost:8080}
        description: ${API_SERVER_PROD_DESCRIPTION:Production Server}
    mail:
      from: ${MAIL_FROM:noreply@example.com}
      fromName: ${MAIL_FROM_NAME:Sender Name}
    frontend:
      base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    cors:
      allowed-origins:
        - ${FRONTEND_BASE_URL:http://localhost:3000}
